kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 30d
      replicas: 2
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 50Gi
  alertmanager:
    alertmanagerSpec:
      replicas: 2
